import com.sun.net.httpserver.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.sql.*;import java.util.*;
public class HospitalServer{
 static final int PORT=8080;
 public static void main(String[] a)throws Exception{Class.forName("com.mysql.cj.jdbc.Driver");HttpServer s=HttpServer.create(new InetSocketAddress(PORT),0);s.createContext("/",HospitalServer::staticFile);s.createContext("/api/dashboard",HospitalServer::dashboard);s.createContext("/api/patients",HospitalServer::patients);s.start();System.out.println("OPEN http://localhost:8080");}
 static void staticFile(HttpExchange e)throws IOException{String p=e.getRequestURI().getPath();if(p.equals("/"))p="/index.html";File f=new File("web"+p).getCanonicalFile();File b=new File("web").getCanonicalFile();if(!f.toPath().startsWith(b.toPath())||!f.isFile()){send(e,404,"Not found","text/plain");return;}String t=p.endsWith(".css")?"text/css":p.endsWith(".js")?"application/javascript":"text/html";byte[]x=java.nio.file.Files.readAllBytes(f.toPath());e.getResponseHeaders().set("Content-Type",t+";charset=UTF-8");e.sendResponseHeaders(200,x.length);try(OutputStream o=e.getResponseBody()){o.write(x);}}
 static void dashboard(HttpExchange e)throws IOException{try(Connection c=DBConnection.getConnection();Statement s=c.createStatement()){send(e,200,"{\"patients\":"+count(s,"SELECT COUNT(*) FROM patients")+",\"doctors\":"+count(s,"SELECT COUNT(*) FROM doctors")+",\"appointments\":"+count(s,"SELECT COUNT(*) FROM appointments")+",\"bills\":"+count(s,"SELECT COUNT(*) FROM bills")+"}","application/json");}catch(Exception x){send(e,500,"{\"error\":\""+j(x.getMessage())+"\"}","application/json");}}
 static void patients(HttpExchange e)throws IOException{try(Connection c=DBConnection.getConnection()){if(e.getRequestMethod().equals("GET")){try(Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT patient_id,name,age,gender,phone,address FROM patients ORDER BY patient_id DESC")){StringBuilder b=new StringBuilder("[");boolean f=true;while(r.next()){if(!f)b.append(',');f=false;b.append("{\"id\":").append(r.getInt(1)).append(",\"name\":\"").append(j(r.getString(2))).append("\",\"age\":").append(r.getInt(3)).append(",\"gender\":\"").append(j(r.getString(4))).append("\",\"phone\":\"").append(j(r.getString(5))).append("\",\"address\":\"").append(j(r.getString(6))).append("\"}");}send(e,200,b.append(']').toString(),"application/json");}}else if(e.getRequestMethod().equals("POST")){Map<String,String>x=parse(new String(e.getRequestBody().readAllBytes(),StandardCharsets.UTF_8));try(PreparedStatement p=c.prepareStatement("INSERT INTO patients(name,age,gender,phone,address) VALUES(?,?,?,?,?)")){p.setString(1,x.getOrDefault("name",""));p.setInt(2,Integer.parseInt(x.getOrDefault("age","0")));p.setString(3,x.getOrDefault("gender",""));p.setString(4,x.getOrDefault("phone",""));p.setString(5,x.getOrDefault("address",""));p.executeUpdate();}send(e,200,"{\"success\":true}","application/json");}else send(e,405,"Method not allowed","text/plain");}catch(Exception x){send(e,500,"{\"error\":\""+j(x.getMessage())+"\"}","application/json");}}
 static long count(Statement s,String q)throws SQLException{try(ResultSet r=s.executeQuery(q)){r.next();return r.getLong(1);}}
 static Map<String,String>parse(String z){Map<String,String>m=new HashMap<>();for(String q:z.split("&")){String[]a=q.split("=",2);if(a.length==2)m.put(dec(a[0]),dec(a[1]));}return m;}static String dec(String s){try{return URLDecoder.decode(s,StandardCharsets.UTF_8);}catch(Exception e){return s;}}static String j(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n"," ");}static void send(HttpExchange e,int c,String s,String t)throws IOException{byte[]b=s.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type",t+";charset=UTF-8");e.sendResponseHeaders(c,b.length);try(OutputStream o=e.getResponseBody()){o.write(b);}}
}
